server:
    port: 7575
# =======================================
# = Spring Configuration
# =======================================
spring:
    application:
        name: backend-api
    datasource:
        url: jdbc:sqlserver://fhictodin.database.windows.net:1433;database=Lunchtag
        username: odin2001@fhictodin
        password: ICTiscool123
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.jdbc.lob.non_contextual-creation: true