server:
    port: 7575
# =======================================
# = Spring Configuration
# =======================================
spring:
    application:
        name: backend-api
    datasource:
        url: jdbc:mysql://localhost/lunchtagresource?serverTimezone=UTC
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate.jdbc.lob.non_contextual-creation: true