server:
    port: 7575
# =======================================
# = Spring Configuration
# =======================================
spring:
    application:
        name: backend-api

    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:mem:database
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect